# Generated by Django 3.2.5 on 2021-08-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(choices=[('KENYAN', 'Kenyan'), ('RWANDAN', 'Rwandan'), ('UGANDAN', 'Ugandan'), ('SOUTH SUDANEESE', 'South Sudaneese')], default='Kenyan', max_length=15)),
                ('class_name', models.CharField(blank=True, choices=[('LOVELACE', 'Lovelace'), ('ANITA_B', 'AnitaB'), ('LISALAB', 'LisaLab')], default='AnitaB', max_length=12, null=True)),
                ('id_number', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('academic_year', models.IntegerField(blank=True, null=True)),
                ('medical_report', models.FileField(upload_to='')),
                ('guardian_name', models.CharField(max_length=40)),
                ('profile_image', models.ImageField(upload_to='Images')),
            ],
        ),
    ]
