# Generated by Django 3.2.5 on 2021-08-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(choices=[('LOVELACE', 'Lovelace'), ('ANITA_B', 'AnitaB'), ('LISALAB', 'LisaLab')], default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='medical_report',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('KENYAN', 'Kenyan'), ('RWANDAN', 'Rwandan'), ('UGANDAN', 'Ugandan'), ('SOUTH SUDANEESE', 'South Sudaneese')], default='Kenyan', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='', upload_to='Images'),
            preserve_default=False,
        ),
        ]
