# Generated by Django 3.2.5 on 2021-08-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(choices=[('LOVELACE', 'Lovelace'), ('ANITA_B', 'AnitaB'), ('LISALAB', 'LisaLab')], default='AnitaB', max_length=15),
        ),
    ]
