# Generated by Django 3.2.5 on 2021-08-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210804_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, choices=[('LOVELACE', 'Lovelace'), ('ANITA_B', 'AnitaB'), ('LISALAB', 'LisaLab')], max_length=12, null=True),
        ),
    ]
