# Generated by Django 3.2.5 on 2021-08-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210820_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
