# Generated by Django 3.2.5 on 2021-08-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210821_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, choices=[('LOVELACE', 'Lovelace'), ('ANITA_B', 'AnitaB'), ('LISALAB', 'LisaLab')], default='AnitaB', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Kenyan', 'Kenyan'), ('Rwandan', 'Rwandan'), ('Ugandan', 'Ugandan'), ('South Sudaneese', 'South Sudaneese')], default='Kenyan', max_length=15),
        ),
    ]
