# Generated by Django 3.2.5 on 2021-08-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('second_name', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6)),
                ('joining_date', models.DateField()),
                ('salary', models.BigIntegerField()),
                ('city', models.CharField(max_length=12)),
                ('image', models.FileField(upload_to='')),
                ('resume', models.FileField(upload_to='')),
                ('contract', models.FileField(upload_to='')),
            ],
        ),
    ]
