# Generated by Django 3.2.5 on 2021-08-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='company',
            field=models.CharField(max_length=30),
        ),
    ]
