# Generated by Django 3.2.5 on 2021-08-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_trainer_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='image',
        ),
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='contract',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='resume',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
